# Change these first
owner: IslandHQ # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Vultr-MCS1
    url: https://mcs1.zo3.red
  - name: Vultr-MCS2
    url: https://mcs2.zo3.red

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.zo3.red
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**レインボークエスト** で使用しているサーバの稼働時間とステータスページを表示しています。"
  introMessage: "これは、**リアルタイム** データ であり [GitHub repository](https://github.com/IslandHQ/uptime) からのリアルタイムデータを使用するステータスページです。サーバーは必要なく — GitHub Actions, Issues, and Pages - だけで構成されています。"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
